name: 'tsql_utils_dbt_audit_helper_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

require-dbt-version: [">=1.0.0", "<2.0.0"]

dispatch:
  - macro_namespace: audit_helper
    search_order: ['tsql_utils', 'audit_helper']

# TODO remove these variables in the next release
vars:
  audit_helper_dispatch_list: ['tsql_utils']

models:
  audit_helper_integration_tests: 
    +materialized: table