
name: 'tsql_utils_dbt_utils_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

require-dbt-version: [">=1.0.0", "<2.0.0"]

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['tsql_utils_dbt_utils_integration_tests', 'tsql_utils', 'dbt_utils']

# TODO remove these variables in the next release
vars:
  dbt_utils_dispatch_list: ['tsql_utils', 'tsql_utils_dbt_utils_integration_tests']

models:
  dbt_utils_integration_tests:
    +as_columnstore: "{{ target.type != 'sqlserver' }}"
    +enabled: true
    cross_db_utils:
      test_split_part: &not-synapse
        # no XML datatype in synapse
        +enabled: "{{ target.type != 'synapse' }}"
      # BROKEN DUE TO SYNAPSE SEED LOADING EMPTY CSV VALS AS EMPTY STRINGS
      # see: https://github.com/dbt-msft/dbt-synapse/issues/36
      test_dateadd: *not-synapse
      test_datediff: *not-synapse
      test_hash: *not-synapse
      test_last_day: *not-synapse
    web:
      # TODO: fix these!
      # see: https://github.com/dbt-msft/tsql-utils/issues/66
      test_url_host: &disabled
        +enabled: false
      test_url_path: *disabled
      test_urls: *disabled
    sql:
      # BROKEN BC MACROS ARE UNPORTED STILL
      test_generate_series: *disabled
      test_get_column_values: *disabled
      test_get_relations_by_pattern: *disabled
      test_get_relations_by_prefix_and_union: *disabled
      # broken bc TSQL will never support
      test_groupby: *disabled
      test_union: *disabled
      test_unpivot_bool: *disabled
    materializations:
      # TODO: fix error
      # https://github.com/dbt-msft/tsql-utils/issues/67
      test_insert_by_period: *disabled
  # intractable nested CTEs from
  # https://github.com/calogica/dbt-date/pull/30
  dbt_date_integration_tests:
    dates: *disabled
    dim_week: *disabled
    dim_hour: *disabled

tests:
  dbt_utils_integration_tests: *disabled
seeds:
  +quote_columns: false
  dbt_utils_integration_tests:
    schema_tests:
      data_test_sequential_timestamps:
        +column_types:
          my_timestamp: datetime2
      # can't override dbt_utils's test def args
      data_test_unique_where: *disabled
      data_test_not_null_where: *disabled
      # more like above: something weird happening: `Incorrect syntax near '<'.`
      data_test_mutually_exclusive_ranges_with_gaps_zero_length: *disabled
      data_test_mutually_exclusive_ranges_no_gaps: *disabled
      data_test_mutually_exclusive_ranges_with_gaps: *disabled

    cross_db:
      data_date_trunc:
        +column_types:
          updated_at: datetime
          day: date
          month: date

      data_dateadd:
        +column_types:
          from_time: datetime
          result: datetime

      data_datediff:
        +column_types:
          first_date: datetime
          second_date: datetime

      data_width_bucket:
        +column_types:
          num_buckets: integer
          min_value: float
          max_value: float
    sql:
      data_events_20180103:
        +schema: events
      # not yet ported, or can't be??
      data_unpivot_bool: *disabled
      data_unpivot_bool_expected: *disabled
      # data_get_query_results_as_dict: *not-synapse
